### ISSUE TITLE
Proxy use external code

### ISSUE THREAD

**Issue by uwejan** [absmach/mproxy#18]
Hi. Good work.
I already have my code on java or other languages. I can use webhooks of vernemq and its work8ng gooe. But with more and more connections it gets slow in general.
Thus i am just guessing here please correct me. That taking auth or payload logging outside the broker will keep the broker lightweight and more efficient. 
And that brings me to the proxy, is it possible to auth decline and log payload using code from different language than go. Learning go would be beneficial but am time limited i would really appreciate an example if possible with other languages. 
Moreover will using the proxy for the mentioned tasks above make the broker more efficient. In case of 10k concurrent connections just an example here.
All appreciated. Thanks.

**Comment by dusanb94** [comment]
Hello, @uwejan. At the moment, mProxy is used as a lib, and for that reason, it's impossible to use it in any other language. You can use the Mainflux MQTT adapter as an example of mProxy utilization (https://github.com/mainflux/mainflux/tree/master/mqtt). Mainflux MQTT adapter is using mProxy to send authorization gRPC requests and processes MQTT packet according to the response. If you have a similar authorization API, we can help you to modify this example to work with your particular case.

mProxy should offload a lot of work from the broker, and improve performance if the bottleneck is authorization itself. However, from our experience with all kinds of MQTT brokers, authorization (regardless of if it's done using mProxy or in a broker-native way) is not the bottleneck, but simply handling many connections, especially if we're talking QoS2 and horizontal scaling with load balancing. The broker needs to keep up with all of that and it comes at the cost of performance. I would advise you first to test performance without authorization to double-check if that's the problem. If it is, an implementation similar to the Mainflux MQTT adapter will help, assuming that your authorization method or Auth API is not the bottleneck.

We've just recently started working on a full-blown IoT gate that will be using mProxy lib to create a service that will be doing TLS termination and authentication for supported protocols. It's in the early stage of development and here you can find the repo: https://github.com/mainflux/mgate.

**Comment by drasko** [comment]
@dusanb94 @uwejan @blokovi for that matters, we might consider in the future exposing gRPC API and making it language agnostic.

It would be a nice feature.

**Comment by dusanb94** [comment]
Actually, you can already do it as long as your Auth service implements this gRPC API: https://github.com/mainflux/mainflux/blob/e272d9f7ad39eda5c97d3c4a34b0e80521c55f27/authn.proto#L10. At the moment, this API is adjusted to Mainflux needs, and we'll probably have to enrich it for more generic use.

**Comment by drasko** [comment]
@uwejan you can check Mainflux MQTT benchmarks here: https://github.com/mainflux/benchmark.

They are done with mProxy and VerneMQ, everything is done in QoS2 and with authorization gRPC calls from mProxy (so "the real deal").

10k msg/sec without message loss is achieved on relatively modest k8s cluster (running full Mainflux, not only MQTT parts). Detailed reports are [here](https://github.com/mainflux/benchmark/blob/master/reports/README.md).

**Comment by dborovcanin** [comment]
This is a stale one, and we have no plans of adding support for other languages at the moment.
