### ISSUE TITLE
MQTT over WS is broken

### ISSUE THREAD

**Issue by dborovcanin** [absmach/mproxy#65]
**BUG REPORT**

1. What were you trying to achieve?
I'm trying to send an MQTT message using Websockets.

2. What are the expected results?
I expect it to succeed.

3. What are the received results?
I'm unable to connect using WS and I don't see any logs on the MQTT adapter.

5. What are the steps to reproduce the issue?
6. Run the Magistrala composition. Provision Thing and Channel, connect them and try to send MQTT message over WS. 

7. In what environment did you encounter the issue?
I use the latest Magistrala, in the latest Docker env, but the bug seems to be related to mProxy.

8. Additional information you deem important:
N/A

**Comment by felixgateru** [comment]
From my testing, the issue is not with mproxy but with magistrala. From test MQTT over WS works with client and mosquitto broker. The issue is with target URL formatting in Magistrala which does not have `ws://` and `/mqtt`
